### ISSUE TITLE
A question about assembly of PCB ...

### ISSUE THREAD

**Issue by softfoot** [podonoghue/Jim_Williams_Pulse_Generator#3]
Looking at the pictures of an assembled board you have cut the collector lead off so I assume you rely on contact betweek the can of the transistor and the copper pad that surrounds it ??

Does it need to be soldered or is a push fit enough (my transistors are a little loose) ??
Would a bit of soft copper wire to make it a tight push fit be OK ??

Regards,
Dave

**Comment by podonoghue** [comment]
I soldered the can of the transistor which I confirmed was connected to the appropriate pin.
This may not be a desired technique but I had no problem.
Please note the feedback on the variable results due to variations in the transistors.
Also note that I used it with a digital scope so low repetition rate wasn't an issue.

**Comment by softfoot** [comment]
Thanks for that very prompt response.
I managed to find some 2n2369's (NOT "A's") on ebay from a couple of sources and tested them on a "lash up" and found that they all worked at <80V and were consistent in their operation on my TDS744A.
I'll start soldering when I find my reading glasses (Even then 0805's are a bit of a struggle. At least you didn't use 0402's which dissapear in the slightest draft ) :-)
Regards,
Dave
